// <auto-generated />
using System;
using IsgCevreYonetim.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsgCevreYonetim.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IlId")
                        .HasColumnType("int");

                    b.Property<int?>("IlceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SgkIsyeriKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SgkIsyeriSicilNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliKisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchKodu")
                        .IsUnique();

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.HasIndex("CompanyId", "IsDeleted", "IsActive")
                        .HasDatabaseName("IX_Branches_CompanyId_IsDeleted_IsActive");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Cinsiyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Cinsiyetler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.DashboardGuncelleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("SayfaAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Kategori", "Durum", "Sira", "IsDeleted")
                        .HasDatabaseName("IX_DashboardGuncellemeleri_Kategori_Durum_Sira_IsDeleted");

                    b.ToTable("DashboardGuncellemeleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyKodu")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentKodu")
                        .IsUnique();

                    b.HasIndex("BranchId", "IsDeleted", "IsActive")
                        .HasDatabaseName("IX_Departments_BranchId_IsDeleted_IsActive");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IlId", "Ad")
                        .IsUnique();

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KayipGun")
                        .HasColumnType("int");

                    b.Property<DateTime>("KazaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mudahale")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MudahaleSekliId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RaporBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RaporBitis")
                        .HasColumnType("datetime2");

                    b.Property<string>("SorumluAmirAdSoyad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SorumluAmirPersonelId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VardiyaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GorevId");

                    b.HasIndex("GrupId");

                    b.HasIndex("MudahaleSekliId");

                    b.HasIndex("SorumluAmirPersonelId");

                    b.HasIndex("UnitId");

                    b.HasIndex("VardiyaId");

                    b.HasIndex("PersonelId", "IsDeleted")
                        .HasDatabaseName("IX_IsKazalari_PersonelId_IsDeleted");

                    b.HasIndex("BranchId", "IsDeleted", "KazaTarihi")
                        .HasDatabaseName("IX_IsKazalari_BranchId_IsDeleted_KazaTarihi");

                    b.ToTable("IsKazalari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArastiranPersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArastirmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IsKazasiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArastiranPersonelId");

                    b.HasIndex("IsKazasiId")
                        .IsUnique();

                    b.ToTable("IsKazasiArastirmalari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IsKazasiArastirmaId")
                        .HasColumnType("int");

                    b.Property<int>("MaddeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaddeId");

                    b.HasIndex("IsKazasiArastirmaId", "MaddeId")
                        .IsUnique();

                    b.ToTable("IsKazasiArastirmaCevaplari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("IsKazasiArastirmaKategorileri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaMadde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId", "Sira");

                    b.ToTable("IsKazasiArastirmaMaddeleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IsKazasiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsKazasiId");

                    b.ToTable("IsKazasiDosyalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyet", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Aciklama").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Baslik").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<bool>("IsDeleted").HasColumnType("bit");
                    b.Property<int>("IsKazasiId").HasColumnType("int");
                    b.Property<DateTime?>("TamamlanmaTarihi").HasColumnType("datetime2");
                    b.Property<DateTime?>("UpdatedDate").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("IsKazasiId");
                    b.ToTable("IsKazasiDuzelticiFaaliyetler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyetDosya", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
                    b.Property<string>("DosyaAdi").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<long>("DosyaBoyutu").HasColumnType("bigint");
                    b.Property<string>("DosyaTipi").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("DosyaYolu").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<bool>("IsDeleted").HasColumnType("bit");
                    b.Property<int>("IsKazasiDuzelticiFaaliyetId").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedDate").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("IsKazasiDuzelticiFaaliyetId");
                    b.ToTable("IsKazasiDuzelticiFaaliyetDosyalari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiSahit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("IsKazasiId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("IsKazasiId", "PersonelId")
                        .IsUnique();

                    b.ToTable("IsKazasiSahitleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MudahaleSekli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("MudahaleSekilleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.OnlineKullaniciOturumu", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("SessionKey");

                    b.HasIndex("PersonelId")
                        .HasDatabaseName("IX_OnlineKullaniciOturumlari_PersonelId");

                    b.HasIndex("CompanyId", "BranchId", "LastSeenUtc")
                        .HasDatabaseName("IX_OnlineKullaniciOturumlari_Scope_LastSeenUtc");

                    b.ToTable("OnlineKullaniciOturumlari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajGrubu", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Ad").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<int>("CompanyId").HasColumnType("int");
                    b.Property<int>("BranchId").HasColumnType("int");
                    b.Property<int>("KurucuPersonelId").HasColumnType("int");
                    b.Property<DateTime>("OlusturmaUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "BranchId");
                    b.ToTable("MesajGruplari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajEki", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<long?>("OzelMesajId").HasColumnType("bigint");
                    b.Property<long?>("GrupMesajiId").HasColumnType("bigint");
                    b.Property<string>("DosyaAdi").IsRequired().HasMaxLength(180).HasColumnType("nvarchar(180)");
                    b.Property<string>("DepoAdi").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("IcerikTuru").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<long>("Boyut").HasColumnType("bigint");
                    b.HasKey("Id");
                    b.HasIndex("OzelMesajId");
                    b.HasIndex("GrupMesajiId");
                    b.ToTable("MesajEkleri", t => t.HasCheckConstraint("CK_MesajEkleri_TekMesaj", "([OzelMesajId] IS NULL AND [GrupMesajiId] IS NOT NULL) OR ([OzelMesajId] IS NOT NULL AND [GrupMesajiId] IS NULL)"));
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajGrubuUyelik", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("GrupId").HasColumnType("int");
                    b.Property<int>("PersonelId").HasColumnType("int");
                    b.Property<int>("DavetEdenPersonelId").HasColumnType("int");
                    b.Property<DateTime>("DavetUtc").HasColumnType("datetime2");
                    b.Property<DateTime?>("KabulUtc").HasColumnType("datetime2");
                    b.Property<DateTime?>("RedUtc").HasColumnType("datetime2");
                    b.Property<DateTime?>("SonOkumaUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("GrupId", "PersonelId").IsUnique();
                    b.HasIndex("PersonelId", "KabulUtc", "RedUtc");
                    b.ToTable("MesajGrubuUyelikleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajGrubuMesaji", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("GrupId").HasColumnType("int");
                    b.Property<int>("GonderenPersonelId").HasColumnType("int");
                    b.Property<string>("Icerik").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTime>("GonderimUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("GrupId", "Id");
                    b.ToTable("MesajGrubuMesajlari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajPushAboneligi", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("PersonelId").HasColumnType("int");
                    b.Property<string>("Endpoint").IsRequired().HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                    b.Property<string>("EndpointHash").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("P256dh").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("Auth").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("EndpointHash").IsUnique();
                    b.HasIndex("PersonelId");
                    b.ToTable("MesajPushAbonelikleri");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.OzelMesaj", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("CompanyId").HasColumnType("int");
                    b.Property<int>("BranchId").HasColumnType("int");
                    b.Property<int>("GonderenPersonelId").HasColumnType("int");
                    b.Property<int>("AliciPersonelId").HasColumnType("int");
                    b.Property<string>("Icerik").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTime>("GonderimUtc").HasColumnType("datetime2");
                    b.Property<DateTime?>("OkunmaUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "BranchId", "AliciPersonelId", "OkunmaUtc");
                    b.HasIndex("CompanyId", "BranchId", "GonderenPersonelId", "GonderimUtc");
                    b.ToTable("OzelMesajlar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100000L);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CinsiyetId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailDogrulandi")
                        .HasColumnType("bit");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KilitlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilResmi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SifreSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SonGirisIpAdresi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SonGirisUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GorevId");

                    b.HasIndex("GrupId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.HasIndex("YetkiId");

                    b.HasIndex("BranchId", "AktifMi", "IsDeleted")
                        .HasDatabaseName("IX_Personeller_BranchId_AktifMi_IsDeleted");

                    b.HasIndex("CompanyId", "BranchId", "IsDeleted")
                        .HasDatabaseName("IX_Personeller_CompanyId_BranchId_IsDeleted");

                    b.HasIndex("BranchId", "Ad", "IsDeleted", "AktifMi")
                        .HasDatabaseName("IX_Personeller_BranchId_Ad_IsDeleted_AktifMi");

                    b.HasIndex("BranchId", "Soyad", "IsDeleted", "AktifMi")
                        .HasDatabaseName("IX_Personeller_BranchId_Soyad_IsDeleted_AktifMi");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Sayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Sayfalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UnitAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitKodu")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "IsDeleted", "IsActive")
                        .HasDatabaseName("IX_Units_DepartmentId_IsDeleted_IsActive");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Vardiya", b =>
                {
                    b.Property<int>("VardiyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VardiyaId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VardiyaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VardiyaId");

                    b.HasIndex("VardiyaAdi")
                        .IsUnique();

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Yetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.YetkiSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ekle")
                        .HasColumnType("bit");

                    b.Property<bool>("Goster")
                        .HasColumnType("bit");

                    b.Property<bool>("Guncelle")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SayfaId")
                        .HasColumnType("int");

                    b.Property<bool>("Sil")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SayfaId");

                    b.HasIndex("YetkiId", "BranchId", "SayfaId")
                        .IsUnique();

                    b.HasIndex("YetkiId", "BranchId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_YetkiSayfalar_YetkiId_BranchId_IsActive_IsDeleted");

                    b.ToTable("YetkiSayfalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.YetkiSube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LokasyonSecebilir")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("YetkiId", "BranchId")
                        .IsUnique();

                    b.ToTable("YetkiSubeler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Branch", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Il", "Il")
                        .WithMany("Branches")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Ilce", "Ilce")
                        .WithMany("Branches")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Il");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Department", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Branch", "Branch")
                        .WithMany("Departments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Ilce", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasi", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.MudahaleSekli", "MudahaleSekli")
                        .WithMany("IsKazalari")
                        .HasForeignKey("MudahaleSekliId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Personel", "SorumluAmirPersonel")
                        .WithMany()
                        .HasForeignKey("SorumluAmirPersonelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Vardiya", "Vardiya")
                        .WithMany("IsKazalari")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict);
                        

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("Gorev");

                    b.Navigation("Grup");

                    b.Navigation("MudahaleSekli");

                    b.Navigation("Personel");

                    b.Navigation("SorumluAmirPersonel");

                    b.Navigation("Unit");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirma", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Personel", "ArastiranPersonel")
                        .WithMany()
                        .HasForeignKey("ArastiranPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasi", "IsKazasi")
                        .WithOne("Arastirma")
                        .HasForeignKey("IsgCevreYonetim.Domain.Entities.IsKazasiArastirma", "IsKazasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArastiranPersonel");

                    b.Navigation("IsKazasi");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaCevap", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasiArastirma", "Arastirma")
                        .WithMany("Cevaplar")
                        .HasForeignKey("IsKazasiArastirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaMadde", "Madde")
                        .WithMany("Cevaplar")
                        .HasForeignKey("MaddeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arastirma");

                    b.Navigation("Madde");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaMadde", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaKategori", "Kategori")
                        .WithMany("Maddeler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDosya", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasi", "IsKazasi")
                        .WithMany("Dosyalar")
                        .HasForeignKey("IsKazasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsKazasi");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyet", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasi", "IsKazasi")
                        .WithMany("DuzelticiFaaliyetler")
                        .HasForeignKey("IsKazasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("IsKazasi");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyetDosya", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyet", "DuzelticiFaaliyet")
                        .WithMany("Dosyalar")
                        .HasForeignKey("IsKazasiDuzelticiFaaliyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("DuzelticiFaaliyet");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiSahit", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.IsKazasi", "IsKazasi")
                        .WithMany("Sahitler")
                        .HasForeignKey("IsKazasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IsKazasi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Personel", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Branch", "Branch")
                        .WithMany("Personeller")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Cinsiyet", "Cinsiyet")
                        .WithMany("Personeller")
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Company", "Company")
                        .WithMany("Personeller")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Department", "Department")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Gorev", "Gorev")
                        .WithMany("Personeller")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Grup", "Grup")
                        .WithMany("Personeller")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Unit", "Unit")
                        .WithMany("Personeller")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Yetki", "Yetki")
                        .WithMany("Personeller")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Cinsiyet");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Gorev");

                    b.Navigation("Grup");

                    b.Navigation("Unit");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Sayfa", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Sayfa", "Parent")
                        .WithMany("SubPages")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Unit", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Department", "Department")
                        .WithMany("Units")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.YetkiSayfa", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Sayfa", "Sayfa")
                        .WithMany("YetkiSayfalar")
                        .HasForeignKey("SayfaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Yetki", "Yetki")
                        .WithMany("YetkiSayfalar")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Sayfa");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.YetkiSube", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsgCevreYonetim.Domain.Entities.Yetki", "Yetki")
                        .WithMany("YetkiSubeler")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Cinsiyet", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Department", b =>
                {
                    b.Navigation("Personeller");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Gorev", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Grup", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Il", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Ilce", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasi", b =>
                {
                    b.Navigation("Arastirma");

                    b.Navigation("Dosyalar");

                    b.Navigation("DuzelticiFaaliyetler");

                    b.Navigation("Sahitler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiDuzelticiFaaliyet", b =>
                {
                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MudahaleSekli", b =>
                {
                    b.Navigation("IsKazalari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajGrubuUyelik", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.MesajGrubu", null)
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajEki", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.OzelMesaj", "OzelMesaj")
                        .WithMany().HasForeignKey("OzelMesajId").OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("IsgCevreYonetim.Domain.Entities.MesajGrubuMesaji", "GrupMesaji")
                        .WithMany().HasForeignKey("GrupMesajiId").OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("OzelMesaj");
                    b.Navigation("GrupMesaji");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.MesajGrubuMesaji", b =>
                {
                    b.HasOne("IsgCevreYonetim.Domain.Entities.MesajGrubu", null)
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirma", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaKategori", b =>
                {
                    b.Navigation("Maddeler");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.IsKazasiArastirmaMadde", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Sayfa", b =>
                {
                    b.Navigation("SubPages");

                    b.Navigation("YetkiSayfalar");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Vardiya", b =>
                {
                    b.Navigation("IsKazalari");
                });

            modelBuilder.Entity("IsgCevreYonetim.Domain.Entities.Yetki", b =>
                {
                    b.Navigation("Personeller");

                    b.Navigation("YetkiSayfalar");

                    b.Navigation("YetkiSubeler");
                });
#pragma warning restore 612, 618
        }
    }
}
